### ISSUE TITLE
Need a description of the project

### ISSUE THREAD

**Issue by mrtineide** [inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found#10]
As in the checklist/"retteskjema" says:
![Beskrivelse av prosjektet, 5 poeng](https://user-images.githubusercontent.com/43970264/107690771-db096c00-6caa-11eb-952f-587a5b8d7e05.png)
we need a description of the project itself, like what, why and how.
Should we add this in the README.md?
- [x] Done?

**Comment by BelminH** [comment]
I think that it should be in the README.md

**Comment by mrtineide** [comment]
@KimAndreG did this!
