### ISSUE TITLE
Manglende møtereferater

### ISSUE THREAD

**Issue by mrtineide** [inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found#3]
Etter å ha lest gjennom de neste obligene så så jeg at vi skal levere møtereferater. 
Det er visst det første punktet på retteskjema for oblig 1 som de har. 
Det burde vi har før #2 merges.

**Comment by TheLimeFreak** [comment]
Fikset [Møtereferat 2](https://github.com/inf112-v21/Runtime-Terror-Import-Team_Name-Error-404-Team-Name-Not-Found/wiki/02_2021-02-05T1000).

**Comment by mrtineide** [comment]
@OdinBjerga fikset Møtereferat 1
